# Generated by Django 3.1 on 2020-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('hasil', models.CharField(blank=True, max_length=2)),
                ('update', models.DateTimeField(auto_now=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
